# Settings
markdown: kramdown
permalink: pretty
url: https://cactuscollective.tech
baseurl:

# Site
title: The Cactus Collective
description: "Opposing gender discrimination, oppression, and retaliation in tech."

# Social
social:
#  - title: twitter
#    url: https://twitter.com/cactuscollectv
  - title: github
    url: https://github.com/cactus-collective


